apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: redis
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: redis
    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
          - mountPath: /usr/local/etc/redis/
            name: config
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
      volumes:
      - name: config
        configMap:
          name: redis-configmap
          items:
          - key: redis.conf
            path: redis.conf
status: {}
