@Library('tpl@helm-support') _

import tpl.ci.node.tplNodeCiPipeline

parameters {
      string(defaultValue: 'shelleg',     description: 'docker repository prefix name which defaults to shelleg', name: 'dockerRegistryPrefix')
      string(defaultValue: 'latest',      description: 'microservice tag defaults to config',                     name: 'containerTag')
      string(defaultValue: 'msa-pinger',  description: 'microservice name',                                       name: 'containerName')
      string(defaultValue: 'msa-pinger',  description: 'microservice Dockerfile\'s relative path',                name: 'dockerPath')
  }

node('generic') {

    pipeline = new tplNodeCiPipeline(this)
    pipeline.run()
}
