@Library('tpl@helm-support') _

import tpl.ci.node.tplNodeCiPipeline

parameters {
  string(defaultValue: 'shelleg', description: 'shelleg', name: 'dockerRegistryPrefix')
  string(defaultValue: 'latest', description: '', name: 'containerTag')
  string(defaultValue: true, description: 'msa-poller', name: 'containerName')

  }

node('generic') {

    pipeline = new tplNodeCiPipeline(this)
    pipeline.run()
}
