apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: msa-api
  name: msa-api
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: msa-api
  type: ClusterIP
status:
  loadBalancer: {}
