apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: msa-poller
  name: msa-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: msa-poller
  strategy: {}
  template:
    metadata:
      labels:
        run: msa-poller
    spec:
      containers:
      - env:
        - name: API_URL
          value: ${MSA_API_SERVICE_HOST}:${MSA_API_SERVICE_PORT}
        image: shelleg/msa-poller:latest
        name: msa-poller
        resources: {}
