@Library('tpl@helm-support') _

import tpl.ci.node.tplNodeCiPipeline



node('generic') {
  parameters {
        string(defaultValue: 'shelleg', description: 'shelleg', name: 'dockerRegistryPrefix')
        string(defaultValue: 'config', description: '', name: 'containerTag')
        string(defaultValue: true, description: 'msa-api', name: 'containerName')
    }
  pipeline = new tplNodeCiPipeline(this)
  pipeline.run()
}
